# Generated by Django 2.2.3 on 2019-08-09 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_thing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_logo',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
