# Generated by Django 2.2.3 on 2019-08-09 19:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_thing', '0002_person_person_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_bio',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
